language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: C9t4VvPCrbC+RJKura5PP4K3IOuenyH2XWN0eT1bWPxMVDEPmr5sFKOwOTG0uGj87d/U22xRLIWAyxUd/Lo3eqpuEo45mH3Ch5yE2QiAtacWKr5pGTV1a5KTA43fZ0VaNKCnd4KW+VRFsZ+ExeUbpHLLarzm9TAiQVT/CYSSdK91DL8nUt9lPbrjL48Qx9tawX4kvZg+Ms1oGF3ofF/X/KsJGJnXhz0Kr0Nl3XHQJtzunh7BMMwytL5AWdvEFK+yxgGF0Er3/Pwkqj5R5JDah4FopbN4ko5QfDUuhQeKXVgv9zRy6SddNFXUoqs3Y9zEpa9pOqWRjQd6gseA+yIK582xSMBeImWF4D/Q46N46ZOpx9WjOelscwIQi0yerviuX8ORgBNOSzTw0vSL1h+RqYcrkZgSNvRrfTVdj4VSZjDEswTBlXXOyS1Mdhk11epV9We9A3pulU4rLCVKXmbRR6Jcj18N+sZK+ZAnIrmzLeN6Tg4ta4YUZmCqjadmvkMD9Am4kew+RjnibkDXiZBa2vAsC9PMzi2eCevB3g7LRvwz4ibQlDvoUMwniMW0qDXmdWcx6RI7SGGRJWl+f+E4kSMMVN5R/LZeQLUiK3QGV1ANQVVm9IyDydDHe/SUXzPt4fTJRVt3sybKhq4f9bNQHvXfQUWxeSNPlB5WffKuHO4=
  app: lit-river-19656
