language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: lit-river-19656
  api_key:
    secure: trdOM4ZOAlYlNzXBBacVKqMMaR4LZpA9wLw480B+7ctFTajDTK8ncro1HWoOnJLmOLWuNHND9q/tKaEZbEd5yLL34R8HvkukqtcVqvMmgclw3UftnJTOCjuevRfiuwSkknRxBofhsdzjnfaL5muBF9Ds3c5YRER6tnbCGq36ENbCIlPI03QmcabocyNbiqN5WIUGt82O36TvUib1yAPnaVHfJ5cTXqk1K7TdBlOH6FSKns01sbLaQMv+ocm0RqXTp2ro8ScHGNXEsLKuESXrO9mSMnBfuApGzGosN7c7QQMx/XYYPdvAccdUhz25IZnYtEYTgPc93Azg2SeXLQkRCIIiMTYzqx0ZK8K0IlxNjSjpwDrQatLUM3B0arDGVT7HkIwy6ZH8cQrz0+XYxBfGA5PJhm6fNktiRvWdYUSLr4ceDxOMublMAz9S68kyD5s/FXkK1DwjYUYMXM3sC5J8h89YZ7+bMEq3UrXNTD5fmzxnfOFEYhb6xRD4A95vFis9oapz3O5ZlrKtAvcy3cUd8EsjcWeoOhmiqjtanH1hhxuAIEfAAWxWqfOTFB5RuV9wHpp3Ej3xwsO/JC1DSTJWKgMVllgVpz0WKfudO9je7YqomyC3nvHkU1X8QQ0WROjmjah2zuKw7K5eHAnMh9e6UBa73pxOeMsXvaMmgWNQpxM=
