language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: OdRQ1M5a2laoI3v6ZYc4ot6wKvenDoN78Vgcv5nyAI4PJX9nEDvk4/Lf1MxY1N6xIY8umXrIX5g8vT3psFE8i5roNBD52nDxJ7Db7u1MpGJHbSTkhJ0SGVSEdpu523kVXlG3aFxiu3MGoq+y/9CgxmlbwYeCDiXeGiWlzd4JvfR6qyjULeglJtdHLEdE+o1UnklsAyGxXmsMNeat1rvfNRbBP6JCJzv8zmCcgl1tNcFDQDBJj9brmaySyEoCY7XolB3QHXiMsLw+RIQ5mJYn3IZ1wilpxf3vciFv4kjPW5rfgs39Vorim6iWolT9dd+u94og3KzXc5UhLoMJ6lwP5J8mlwp81NQwyFK27pau6kZnN/qyK90dQN2xtH0huc/IfIpVnO0f6Q4GkHFu7rnCeT1BQ0gznUrCdVqJbwrTobQ1f1hSKxv+qwdkGgHSVaA6xmEiq6dGoKEH01uliDg8VmWpV9hIgDmVxaFCqsQCUuMDs/M908P9rChDhcc2OpRJNlOSH+MOeTU/v5PwRAe3cYMCcACHFVtXR5g3MZ8s6Tb0IgZrWqOd33ULaVQh7zBX8lT8S3fsEIHag79FIlSUcBgrSHpg8vdxi8CvJQUOFilSkGK8uWVOfYtgWUsHdgRA+909YpGGwUr//HsgOo6zKsC5BdEiJV/eRrTtK1Awo6U=
